### PR TITLE
Optimize `PINMemoryCache` remove objects when receive memory warning notification

### PR DESCRIPTION
**Pull request by kinarobin**
If you want remove all objects, there is pointless to remove expired objects

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/132f1734f85a017829cd586791523bae/raw/a63634e00ae9d0d417498a4187b02b54f7a268ff/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/f077db534d684330c5b17ba2e916cd5c/raw/5fa3e2650c884133e07ab6e1d8938eccde50a218/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/d2e3ecb523fdbe0f20a7839a96a077e6/raw/1dec46e8411530ea5cbc596b8d2e3c454f12f43c/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/78c4cc69744ade6cd9ee9eb312fe2670/raw/eec4514d6edac910d324847a856aaf1dbd74540c/log.txt)

**Comment by kinarob** [comment]
@pinterest-ios Could you change build system to **Legacy Build System** for CI? Thanks.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/67cb8f8f6fcf267cf16ea48deefa7935/raw/c54e8886190475464a4e46deb8d138be5d37e317/log.txt)

**Pull request merged**
