### PR TITLE
Fix Xcode 7 warnings

### PR DESCRIPTION
**Pull request by garrettmoon**

### CODE REVIEW

**Comment by jparise** [comment]
I think we should consider adding:

```objc
- (instancetype)init NS_UNAVAILABLE;
```

... to the class extension interface, too.

**Comment by tapz** [comment]
2.0 pods does not seem to have this fix. At least Xcode 7 gives the error.

**Comment by garrettmoon** [comment]
It won't be in cocoa pods until there is a new release.

**Comment by garrettmoon** [comment]
Will try and get one out soon.

**Comment by garrettmoon** [comment]
2.1 should include this.

**Pull request merged**
