### PR TITLE
Switch to GitHub Actions for CI

### PR DESCRIPTION
**Pull request by jparise**
This also bumps our testing target platform to iPhone 8 (from iPhone 7)
because that's the minimum version available in GitHub's environment.

### CODE REVIEW

**Comment by vovasty** [comment]
can we update tests to iOS 13.1 as well? (it means we need to regenerate all snapshots)

**Comment by jparise** [comment]
> can we update tests to iOS 13.1 as well? (it means we need to regenerate all snapshots)

Yes, I'll introduce a multi-version testing matrix now that I've proved it essentially works.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/eba76c97d3bd6a22aa0187bf863c7429/raw/09e725f96a30fe053c45aff8c0b5935045508902/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/caa45e4809a7da4f01ecdf06dcde96cb/raw/b50f5b5a1ed42de283b3c2db54853e3e6ce7e9c3/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/476c59f06a248566b07b96b00cb5c798/raw/18344ae745724df7ad709df8c83ab7448b402109/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/128a36449a0cceee8b86a2473fd34846/raw/6aec04eb46c2f47f19b1dd8c5b8554176cf9424f/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/27b4fe10b8a82556789e9823f740d6da/raw/c993cb6b7ddd3a3075dea1b043d821f2c0fe88a1/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/d956f50583c8a64973ffeb6caa5987c3/raw/41ff03b9b21bec7f47a2ee8192f0d63168ccae0c/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/7c1115b185543fbf52fd36cd8f12e3cd/raw/b0e6b8df451228f36e583074d979f12df5e0ced9/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/0b0a4a2bbd29e9c720ddd5b8f5d83b40/raw/928f9f7ae53fe4f33cdf951a04aebe7449905f60/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/a262fc9db4323cd523fa3f91d20f540e/raw/8e505ccaa583b54c6eefcdf3e3f38c1d23dfa2b8/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/bd31e0ec950cc8ad0bd1fe2af5ff129e/raw/a591f8505c3544b0eb4b3eda1b82884aef702b37/log.txt)

**Comment by garrettmoon** [comment]
Does github have little build status thingies? If so it would be good to update the README.

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/72692ba7eff1e9df71ba003899fb8839/raw/91edc9a07e2389338d614341a164bd293b4c38c9/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/c260af0e744c1c60ed406852457a7982/raw/c2f8c57004d896f74b09628bab2236929875a83f/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/e4ebe6894ac4c45972f9ea9a50732bec/raw/989ab4c390b3a6899eab68fede96b8923e2b007f/log.txt)

**Pull request merged**
