### PR TITLE
[PINMemoryCache] Replace Semaphore with pthread_mutex

### PR DESCRIPTION
**Pull request by Adlai-Holler**
@garrettmoon before you ask… yes, a semaphore killed my parents. 🙃

### CODE REVIEW

**Comment by maicki** [comment]
@Adlai-Holler See #98 maybe we should use the same in this case.

**Comment by garrettmoon** [comment]
The conditional lock is required in the disk case because of the weird initialization we do :/ I think we can use a semaphore directly here. Eventually I'd like to use something that uses an NSLock in debug and a semaphore in production ala the lock in PINRemoteImage.

**Comment by Adlai-Holler** [comment]
I think we should prefer a mutex over a semaphore here. Mutex was built exactly for this case – for one thread to own and block all other threads from acquiring. It's the basis of NSLock. I don't know the implementation details between mutex and semaphore, maybe @johnezang can weight in.

**Comment by garrettmoon** [comment]
@Adlai-Holler Sorry, I meant NSLock in debug, mutex in production :(

**Comment by garrettmoon** [comment]
I'm happy to merge this once the tests pass.

**Comment by Adlai-Holler** [comment]
Oh! Awesome!

**Comment by garrettmoon** [comment]
Thanks @Adlai-Holler !

**Comment by levi** [comment]
semaphores caused Y2K

**Pull request merged**
