### PR TITLE
Propagate the name of the PINCache to the PINMemoryCache #trivial

### PR DESCRIPTION
**Pull request by bolsinga**
It is nice when debugging.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/3d64e5ed1abeece63afcbbbf103c231f/raw/d3431ec07420cbfa69465e6ad1371b8c986a7483/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/dfc95bcc0b306f997041b411333fcb54/raw/f3129da497bc51a826197b3bca42179cf1e57382/log.txt)

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/5055df350949ce52318ae8c2ac3c0f68/raw/170d1213b00d0760242d1bb770a5260f78278d12/log.txt)

**Comment by bolsinga** [comment]
243 ought to help with the tests

**Pull request merged**
