### PR TITLE
Fixed watchos linting errors

### PR DESCRIPTION
**Pull request by benasher44**
- travis.yaml now runs ```pod lib lint```
- Fixed up build_tests.sh to work with recent xcode tools
- Fixed some async-related test failures/flakes

### CODE REVIEW

**Comment by garrettmoon** [comment]
@benasher44 looks like pod lib lint passes, but pod spec lint fails with the same error :(

**Comment by garrettmoon** [comment]
Ohhh, but it may be that it's because this isn't merged. Hold off on investigating.

**Comment by benasher44** [comment]
@garrettmoon ```pod spec lint``` looks at the podspec, and downloads the code pointed to by the spec, and then it does ```pod lib lint```. Since the pod spec is still pointing at the failing tag, that's expected. Once this is merged, you'll need to update the tag. Then, it should pass.

**Comment by benasher44** [comment]
This is also why I didn't have .travis.yaml do ```pod spec lint```, since it'll just be looking at the same code every time :)

**Comment by garrettmoon** [comment]
@benasher44 Thanks for doing this! Let's give it a go!

**Comment by garrettmoon** [comment]
Yeah, that makes sense :)

**Pull request merged**
