### PR TITLE
Optimization `PINMemoryCache` trim to date

### PR DESCRIPTION
**Pull request by kinarobin**
I notice `PINMemoryCache` had some usage for trim to age limit recursively.

Every time ordering the `createdDates` for trim to age is so **expensive**, and we don't use the sort of container any more for other scene.   

So, instead of sort the container, we could delete the expired objects with a `for loop` directly.

Time Complexity： (√n * n + (expired count) )      ->       **n**

### CODE REVIEW

**Comment by kinarob** [comment]
I run all tests locally. No errors occurred!

**Comment by garrettmoon** [comment]
Yes! It's not your fault, it's the build machine, I'll either fix or merge, thank you for the PR!

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by kinarobin** [comment]
@garrettmoon. Could you take a look ? Thanks!

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/46b7e5cc3e0cb33fd0542a05daed3937/raw/9ba821c383da863e19046f720dea0473d05f16f5/log.txt)

**Pull request merged**
