### PR TITLE
Addressed parameter 'object' not found error

### PR DESCRIPTION
**Pull request by AdamBCo**

### CODE REVIEW

**Comment by maicki** [comment]
@AdamBCo Thank for submitting the PR. I cannot reproduce the warning / error while building PINCache. Even if I enable all warnings this does not show up. Can you provide a bit more information          when you are hitting that error. Thanks!

**Comment by AdamBCo** [comment]
@maicki I keep seeing the following warning appear in Xcode.
Screenshot attached below:

screen shot 2017-10-18 at 10 13 17 am

**Comment by garrettmoon** [comment]
@AdamBCo I think you may be on an old version?

**Comment by AdamBCo** [comment]
@garrettmoon Is that change on a different branch? I forked from master. This small change addresses the warning and updates the documentation, which based on my change is currently incorrect.

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by pinterest-ios** [comment]
🚫 CI failed with [log](https://gist.githubusercontent.com/pinterest-ios/94207e1391ef4a460b360569f713ca8b/raw/086f758534dbb48b35c8ce81673e263a26f46329/log.txt)

**Comment by maicki** [comment]
@AdamBCo As @garrettmoon said on master the method currently has the right parameter name. Did you sync your master branch from your fork with the master branch of the origin repo?

**Comment by garrettmoon** [comment]
I'm going to close this out since we haven't heard back. Thanks for your contribution!

**Pull request closed without merging**
