### PR TITLE
Adding Nullability for better optional support for swift

### PR DESCRIPTION
**Pull request by mRs-**

### CODE REVIEW

**Comment by garrettmoon** [comment]
The continuous integration tests won't work until I switch them to use the newest Xcode. This is going to take a bit, so I won't be able to get to this immediately. I will do it ASAP though! Thank you for working on this!

**Comment by benasher44** [comment]
If you update with master, all of the updates have been done to make the CI tests with updated xcode tools

**Comment by mRs-** [comment]
Nice

**Comment by garrettmoon** [comment]
@mRs- mind rebasing against master so that we can make sure this passes the travis build?

**Comment by mRs-** [comment]
will do it!

**Comment by garrettmoon** [comment]
@mRs- I'm going to close this for now, lemme know if you're able to rebase and I'll re-open.

**Pull request closed without merging**
